sudo: required

language: python

services:
  - docker

# we need coveralls and this also prevents travis from running pip install -r requirements.txt
install: pip install coveralls

script:
  - docker-compose build
  - docker-compose run ckan

after_success: coveralls

