language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -e ."
  - "pip install -r requirements.txt"
  - "pip install -r dev_requirements.txt"
# command to run tests
script: coverage run --source=ckanext.ldap setup.py nosetests
after_success: coveralls
