version: "3"

services:
  ckan:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    depends_on:
      - db
      - solr
      - redis
    volumes:
      - .:/base/src/ckanext-ldap

  solr:
    image: ckan/ckan-solr:2.9
    logging:
      driver: none

  db:
    build:
      context: https://github.com/okfn/docker-ckan.git#:postgresql
      args:
        - DATASTORE_READONLY_PASSWORD=password
        - POSTGRES_PASSWORD=password
    environment:
      - DATASTORE_READONLY_PASSWORD=password
      - POSTGRES_PASSWORD=password
    logging:
      driver: none

  redis:
    image: redis:latest
    logging:
      driver: none
