name: Sync branches

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    name: Sync dev and patch branches to latest commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Sync dev branch
        uses: connor-baer/action-sync-branch@main
        with:
          branch: dev
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Sync patch branch
        uses: connor-baer/action-sync-branch@main
        with:
          branch: patch
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
